name: Checks

on:
    push:
        branches:
            - "*"
        tags-ignore:
            - "v*.*.*"

    pull_request:
        branches:
            - "*"

env:
    node_version: 16

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v3

            - name: install node
              uses: actions/setup-node@v3.1.0
              with:
                  node-version: ${{ env.node_version }}

            - name: Install dependencies
              run: yarn install --immutable --immutable-cache --check-cache

            - name: Lint
              run: yarn run lint

            - name: Test
              run: yarn run test:ci

            - name: Build
              run: yarn run build
