name: Publish

on:
    push:
        tags:
            - "v*.*.*"

env:
    node_version: 16

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v3

            - name: Install node
              uses: actions/setup-node@v3.1.0
              with:
                  node-version: ${{ env.node_version }}

            - name: Install dependencies
              run: yarn install --immutable --immutable-cache

            - name: Lint
              run: yarn run lint

            - name: Test
              run: yarn run test:ci

            - name: Build
              run: yarn run build

            - name: Archive production artifacts
              uses: actions/upload-artifact@v2
              with:
                  name: dist
                  path: dist

    publish:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Install node
              uses: actions/setup-node@v3.1.0
              with:
                  node-version: ${{ env.node_version }}

            - name: Install dependencies
              run: yarn install --immutable --immutable-cache

            - name: Download production artifacts for publication
              uses: actions/download-artifact@v2
              with:
                  name: dist
                  path: dist

            - name: Publish to npm
              run: |
                  yarn config set npmAuthToken ${NPM_TOKEN}
                  yarn npm publish
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Extract version
              run: |
                  echo "::set-output name=version::$(jq -r '.version' package.json)"
              id: extract_version

            - name: Create release
              id: create_version_release
              uses: ncipollo/release-action@v1
              with:
                  allowUpdates: false
                  name: ${{steps.extract_version.outputs.version}}
                  token: ${{ secrets.GITHUB_TOKEN }}
